version: "3.9"

services:
  veicles:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_DB
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/app:ro
    environment:
      - NODE_ENV=docker
